### ISSUE TITLE
make 'bulker load' printout more concise

### ISSUE THREAD

**Issue by michalstolarczyk** [databio/bulker#25]
after `bulker load` cmd execution lots of stuff is logged to the screen. Can this be more concise?
What is more, some of the information does not make sense for a bulker newbie -- after each entry:
```
None
None found.
```
entire printout:
```
[mstolarczyk@MichalsMBP test_genomes]: bulker load refgenie -f /Users/mstolarczyk/Uczelnia/UVA/code/refgenie/refgenie_manifest.yaml
Using default config. No config found in env var: BULKERCFG
Bulker config: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/templates/bulker_config.yaml
Executable template: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/bulker/templates/docker_executable.jinja2
That manifest has already been loaded. Overwrite? [y/N] y
Removing all executables in: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
command: samtools
dockerargs: -i
docker_image: quay.io/biocontainers/samtools:1.9--h91753b0_8
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: bowtie2-build
docker_image: quay.io/biocontainers/bowtie2:2.3.5--py37he860b03_0
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: bwa
docker_image: quay.io/biocontainers/bwa:0.7.17--pl5.22.0_2
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: hisat2-build
docker_image: quay.io/biocontainers/hisat2:2.0.4--py35_0
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: bismark_genome_preparation
docker_image: quay.io/biocontainers/bismark:0.18.1--pl5.22.0
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: tabix
docker_image: quay.io/biocontainers/htslib:1.6--0
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: STAR
docker_image: biocontainers/rna-star:v2.5.2bdfsg-1-deb_cv1
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
{'protocol': None, 'namespace': 'biocontainers', 'image': 'rna-star', 'subimage': None, 'tag': 'v2.5.2bdfsg-1-deb_cv1'}
None found.
command: salmon
docker_image: quay.io/biocontainers/salmon:0.11.3--h86b036
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
command: kallisto
docker_image: quay.io/biocontainers/kallisto:0.42.4--2
volumes: ['/tmp']
envvars: ['DISPLAY']
default_crate_folder: /Users/mstolarczyk/bulker_crates
singularity_image_folder: /Users/mstolarczyk/simages
container_engine: docker
default_namespace: bulker
executable_template: docker_executable.jinja2
shell_template: docker_shell.jinja2
build_template: docker_build.jinja2
crates:
  bulker:
    refgenie:
      default: /Users/mstolarczyk/bulker_crates/bulker/refgenie/default
None
None found.
Loading manifest: 'bulker/refgenie:default'. Activate with 'bulker activate bulker/refgenie:default'.
Commands available: samtools, bowtie2-build, bwa, hisat2-build, bismark_genome_preparation, tabix, STAR, salmon, kallisto
```
