### ISSUE TITLE
container-specific volumes not mounting

### ISSUE THREAD

**Issue by lwaldron** [databio/bulker#29]
I'm having trouble getting container-specific volume mounts in bulker 3.0:

```
bulker-3.2$ ls .local/lib/R  #I made these directories in advance, is this necessary?
bulker-3.2$ ls .local/lib/Rdev   #I made these directories in advance, is this necessary?
Levis-Air:~ lw391$ bulker activate waldronlab/bioconductor
Bulker config: /Users/lw391/bulker_config.yaml
Activating bulker crate: waldronlab/bioconductor

bulker-3.2$ _R
Starting interactive docker shell for image 'bioconductor/bioconductor_full:release' and command 'R'
I have no name!@docker-desktop:/Users/lw391$ ls /usr/local/lib/R/host-site-library
ls: cannot access '/usr/local/lib/R/host-site-library': No such file or directory
I have no name!@docker-desktop:/Users/lw391$ exit
bulker-3.2$ exit
Levis-Air:~ lw391$ ls .local/lib/R
Levis-Air:~ lw391$ ls .local/lib/Rdev
ls: .local/lib/Rdev: No such file or directory
Levis-Air:~ lw391$ mkdir .local/lib/Rdev
Levis-Air:~ lw391$ ls .local/lib/R
Levis-Air:~ lw391$ ls .local/lib/Rdev
Levis-Air:~ lw391$ bulker activate waldronlab/bioconductor
Bulker config: /Users/lw391/bulker_config.yaml
Activating bulker crate: waldronlab/bioconductor

bulker-3.2$ _R
Starting interactive docker shell for image 'bioconductor/bioconductor_full:release' and command 'R'
I have no name!@docker-desktop:/Users/lw391$ ls /usr/local/lib/R/host-site-library
ls: cannot access '/usr/local/lib/R/host-site-library': No such file or directory
I have no name!@docker-desktop:/Users/lw391$ exit
bulker-3.2$ _Rdev
Starting interactive docker shell for image 'bioconductor/bioconductor_full:devel' and command 'Rdev'
I have no name!@docker-desktop:/Users/lw391$ ls /usr/local/lib/R/host-site-library
ls: cannot access '/usr/local/lib/R/host-site-library': No such file or directory
I have no name!@docker-desktop:/Users/lw391$ exit
bulker-3.2$ 
```

Here is my bulker_config.yaml:

```
bulker:
  volumes: ['/tmp', '$HOME']
  envvars: ['DISPLAY']
  registry_url: http://hub.bulker.io/
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  container_engine: docker
  default_namespace: bulker
  executable_template: templates/docker_executable.jinja2
  shell_template: templates/docker_shell.jinja2
  build_template: templates/docker_build.jinja2
  crates:
    bulker:
      demo:
        default: /Users/lw391/bulker_crates/bulker/demo/default
    bioconductor:
      bioconductor_full:
        default:
          docker_args: --volume=${HOME}/.local/lib/R:/usr/local/lib/R/host-site-library
        devel:
          docker_args: --volume=${HOME}/.local/lib/Rdev:/usr/local/lib/R/host-site-library
      levi:
        default: /Users/lw391/bulker_crates/bulker/levi/default
    waldronlab:
      bioconductor:
        default: /Users/lw391/bulker_crates/waldronlab/bioconductor/default
      levi:
        default: /Users/lw391/bulker_crates/waldronlab/levi/default
```
