### ISSUE TITLE
--workdir="`pwd`" is ignored when invoking rstudio-server

### ISSUE THREAD

**Issue by lwaldron** [databio/bulker#38]
When invoking rstudio-server in [waldronlab/bioconductor.yaml](https://github.com/databio/hub.bulker.io/blob/e572484016a73be1d987fd463d167b508dd6c565/waldronlab/bioconductor.yaml#L13), the rstudio session starts in the directory `/home/rstudio`, meaning that ``--workdir="`pwd`"`` is ignored. This is inconvenient because the `/home/rstudio` directory is empty, and things like the host `${HOME}/.Renviron` are ignored, and you have to change directories manually e.g. to `/Users/lwaldron`. 

Since rstudio-server is not a command-line operation, one solution is for me to hard-code `dockerargs: "-v $HOME:/home/rstudio"` into the waldronlab/bioconductor.yaml manifest entry for `rstudio-server`. This works, even though my home directory appears under `/home/rstudio`. This setting is specific to the rstudio-server command, so it doesn't seem appropriate to put in bulker_config.yaml. What do you think @nsheff?

**Comment by nsheff** [comment]
that's kind of annoying that it ignores the workdir command. I wonder if this also related to the way these images are created.

> This setting is specific to the rstudio-server command, so it doesn't seem appropriate to put in bulker_config.yaml. 

Well that sounds like a candidate host- and tool-specific setting:

http://docs.bulker.io/en/latest/settings/

So one option is to put that in the bulker config under `tool_args`. However... if you think the desire is universal enough that it will *always* be just '$HOME', and you use '$HOME' instead of some host-specific setting, then you could make an argument that this option is *tool-specific* and *not host-specific*, in which case it goes in the manifest as you suggest. I think either way is acceptable and I'd probably lean toward the way you're doing it.

> Since rstudio-server is not a command-line operation,

I'm not sure why you say that... `rstudio-server` *is* a command-line operation, right?

The other thing you could do that doesn't involve `tool_args` would be to symlink `/home/rstudio` to `$HOME` on each computer. Unfortunately, that's not portable and puts the settings outside of bulker management.

**Comment by lwaldron** [comment]
> Since rstudio-server is not a command-line operation,

By that imprecise statement, I meant that I don't think it will be used in the context of piping, stdin/stdout, or filename arguments where it really matters to preserve `pwd`. It probably does eliminate the possibility of creating a helper that would allow you to, for example, click on a `.Rproj` file and have it opened in RStudio with this command. 

It's not obvious to me from http://docs.bulker.io/en/latest/settings/ how to make a command-specific, as opposed to a tag-specific, setting? E.g. adding the following entries `rstudio-server` and `rstudio-server-dev` lines to my bulker config seems to have no effect:

```
  tool_args:
    bioconductor:
      bioconductor_full:
        default:
          docker_args: --volume=${HOME}/R/bioc-release:/usr/local/lib/R/host-site-library -e PASSWORD=rstudiopassword -p 8787:8787
        devel:
          docker_args: --volume=${HOME}/R/bioc-devel:/usr/local/lib/R/host-site-library -e PASSWORD=rstudiopassword -p 8788:8787
        rstudio-server:
          docker_args: -v $HOME:/home/rstudio
        rstudio-server-dev:
          docker_args: -v $HOME:/home/rstudio
```
