### ISSUE TITLE
inspect requires crate name 

### ISSUE THREAD

**Issue by stolarczyk** [databio/bulker#51]
based on the message below, crate inspecting should be possible in an active crate with no arg provided

```
databio/peppro|~$ bulker -V
bulker 0.5.0
databio/peppro|~$ bulker inspect
Bulker config: /Users/mstolarczyk/bulker_config.yaml
No active create. Inspect requires a provided crate, or a currently active create.
```

**Comment by nsheff** [comment]
yes, it should be... type `echo $BULKERCRATE` and what do you get?

**Comment by nsheff** [comment]
it works here:

```
 ba databio/peppro
Bulker config: /home/nsheff/pCloudSync/env/bulker_config/zither.yaml
Activating bulker crate: databio/peppro
databio/peppro|~$ bulker inspect
Bulker config: /home/nsheff/pCloudSync/env/bulker_config/zither.yaml
Bulker manifest: databio/peppro
Crate path: /home/nsheff/bulker_crates/databio/peppro/default
Available commands: ['cksum', 'paste', 'chmod', 'fastq_pair', 'arch', 'tail', 'unexpand', 'cutadapt', 'expr', 'rm', 'base32', 'python3', 'perl', 'runcon', 'timeout', 'samtools', 'nohup', 'rmdir', 'preseq', 'sleep', 'vdir', 'bowtie2', 'pigz', 'echo', 'base64', 'which', 'bash', 'shuf', 'stty', 'fastqc', 'cp', 'chgrp', 'ptx', 'mkfifo', 'seq', 'du', 'bigWigCat', 'logname', 'factor', 'fastp', 'dircolors', 'java', 'pwd', 'expand', 'sh', 'mkdir', 'whoami', 'R', 'tsort', 'users', 'fmt', 'truncate', 'csplit', 'uptime', 'tee', 'touch', 'false', 'od', 'mv', 'numfmt', 'seqtk', 'b2sum', 'groups', 'id', 'docker', 'seqkit', 'basename', 'cat', 'bedtools', 'nproc', 'unlink', 'md5sum', 'link', 'cut', 'pr', 'shred', 'flash', 'yes', 'lesspipe', 'dir', 'sha512sum', 'tr', 'split', 'hostname', 'Rscript', 'sha256sum', 'chown', 'tty', 'uname', 'pinky', 'grep', 'true', 'wc', 'printf', 'install', 'stdbuf', 'ln', 'mknod', 'df', 'comm', 'sha224sum', 'realpath', 'dd', 'pathchk', 'uniq', 'nl', 'test', 'ls', 'env', 'sha384sum', 'tac', 'fold', 'who', 'wigToBigWig', 'hostid', 'printenv', 'sha1sum', 'join', 'nice', 'stat', 'date', 'awk', 'sed', 'sum', 'sync', 'dirname', 'head', 'sort']
databio/peppro|~$ 

```

**Comment by stolarczyk** [comment]
I get nothing 
```
databio/peppro|~/Uczelnia/UVA/code/peppro$ echo $BULKERCRATE

databio/peppro|~/Uczelnia/UVA/code/peppro$
```

**Comment by nsheff** [comment]
did you re-init?

**Comment by stolarczyk** [comment]
yes, I ran `bulker init -c ...`

**Comment by nsheff** [comment]
do you have these lines?
```
grep rcfile $BULKERCFG
  rcfile: templates/start.sh
  rcfile_strict: templates/start_strict.sh
```

**Comment by stolarczyk** [comment]
```
[mstolarczyk@MichalsMBP ~]: c bulker_config.yaml
bulker:
  volumes: ['$HOME']
  envvars: ['DISPLAY']
  registry_url: http://hub.bulker.io/
  shell_path: ${SHELL}
  shell_rc: ${HOME}/.bashrc
  rcfile: templates/start.sh
  rcfile_strict: templates/start_strict.sh
  default_crate_folder: ${HOME}/bulker_crates
  singularity_image_folder: ${HOME}/simages
  container_engine: docker
  default_namespace: bulker
  executable_template: templates/docker_executable.jinja2
  shell_template: templates/docker_shell.jinja2
  build_template: templates/docker_build.jinja2
  crates:
    databio:
      peppro:
        default: /Users/mstolarczyk/bulker_crates/databio/peppro/default
    bulker:
      alpine:
        default: /Users/mstolarczyk/bulker_crates/bulker/alpine/default
      coreutils:
        default: /Users/mstolarczyk/bulker_crates/bulker/coreutils/default
```
