### ISSUE TITLE
Settings that are both tool-specific and host-specific

### ISSUE THREAD

**Issue by nsheff** [databio/bulker#7]
right now you can do env-specific volumes, which is awesome.
and you can do tool-specific args, which is even awesomer.
but what about tool-specific args that vary by environment? that would be awesomest.

use case: I want to put redis in my crate. I want to attach a local path for the redis db. I don't need that attached to any other tool, so it's tool-specific. I also want a different location attached on a different env, so it's env-specific also. thus, it  fits in neither the bulker config nor the the manifest.

it seems to fit better with env than with tool. I propose a new section in the bulker config for 

```yaml
tool_args:
  redis-server:
    dockerargs: ""
    volumes: ['/local/data:/data']
```

not sure this is the best though...
